# Generated by Django 4.2 on 2023-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedRecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_identifier', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('affiliation', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('publication_date', models.CharField(max_length=255, null=True)),
                ('publication_type', models.CharField(max_length=255, null=True)),
                ('location_identifier', models.CharField(max_length=255, null=True)),
                ('abstract', models.TextField(null=True)),
                ('drug_entities', models.TextField(blank=True, null=True)),
                ('ade_entities', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
