# Generated by Django 4.2 on 2023-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedrecord',
            name='ade_normalized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pubmedrecord',
            name='cuis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
